=== LviatYi/KnownBase/XML/instance/e-library.xsd
<!-- Generated by VS code -->
<xs:schema xmlns="http://lviat.com" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://lviat.com" elementFormDefault="qualified">
    <xs:element name="Library" type="LibraryType" />
    <xs:element name="Book" type="BookType" />
    <xs:element name="Author" type="AuthorType" />
    <xs:element name="Publisher" type="PublisherType" />
    <xs:element name="PublisherAddress" type="PublisherAddressType" />

    <xs:attributeGroup name="BookAttrGroup">
        <xs:attribute name="ISBN" type="ISBNType" use="required" />
    </xs:attributeGroup>
    <xs:element name="BookName" type="BookNameType" />
    <xs:element name="AuthorName" type="AuthorNameType" />
    <xs:element name="Gender" type="GenderType" />
    <xs:element name="PublisherName" type="PublisherNameType" />
    <xs:element name="Province" type="ProvinceType" />
    <xs:element name="City" type="CityType" />
    <xs:element name="AddressDetail" type="AddressDetailType" />
    <xs:element name="Price" type="PriceType" />
    <xs:element name="BookNumber" type="BookNumberType" />
    <xs:element name="PublishDate" type="PublishDateType" />
    <xs:element name="CatalogDateTime" type="CatalogDateTimeType" />
    <xs:element name="InStoreDateTime" type="InStoreDateTimeType" />

    <xs:complexType name="LibraryType">
        <xs:sequence>
            <xs:element ref="Book" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="BookType">
        <xs:sequence>
            <xs:element ref="BookName" />
            <xs:element ref="Author" maxOccurs="unbounded" />
            <xs:element ref="Publisher" />
            <xs:element ref="Price" />
            <xs:element ref="BookNumber" />
            <xs:element ref="PublishDate" />
            <xs:element ref="CatalogDateTime" />
            <xs:element ref="InStoreDateTime" />
        </xs:sequence>
        <xs:attributeGroup ref="BookAttrGroup" />
    </xs:complexType>
    <xs:complexType name="AuthorType">
        <xs:sequence>
            <xs:element ref="AuthorName" />
            <xs:element ref="Gender" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="PublisherType">
        <xs:sequence>
            <xs:element ref="PublisherName" />
            <xs:element ref="PublisherAddress" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="PublisherAddressType">
        <xs:sequence>
            <xs:element ref="Province" />
            <xs:element ref="City" />
            <xs:element ref="AddressDetail" />
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="ISBNType">
        <xs:restriction base="xs:string">
            <xs:maxLength value="17" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="BookNameType">
        <xs:restriction base="xs:string">
            <xs:maxLength value="50" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="AuthorNameType">
        <xs:restriction base="xs:string">
            <xs:maxLength value="10" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="GenderType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="男" />
            <xs:enumeration value="女" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="PublisherNameType">
        <xs:restriction base="xs:string">
            <xs:maxLength value="50" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ProvinceType">
        <xs:restriction base="xs:string">
            <xs:maxLength value="10" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="CityType">
        <xs:restriction base="xs:string">
            <xs:maxLength value="10" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="AddressDetailType">
        <xs:restriction base="xs:string">
            <xs:maxLength value="50" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="PriceType">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="BookNumberType">
        <xs:restriction base="xs:nonNegativeInteger"></xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="PublishDateType">
        <xs:restriction base="xs:date"></xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="CatalogDateTimeType">
        <xs:restriction base="xs:dateTime"></xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="InStoreDateTimeType">
        <xs:restriction base="xs:dateTime"></xs:restriction>
    </xs:simpleType>
</xs:schema>

=== LviatYi/KnownBase/XML/instance/e-library-instance2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Library xmlns="http://lviat.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://lviat.com e-library.xsd">
    <Book ISBN="978-7-5606-2118-0">
        <BookName>XML案例教程</BookName>
        <Author>
            <AuthorName>眭碧霞</AuthorName>
            <Gender>女</Gender>
        </Author>
        <Author>
            <AuthorName>郭永洪</AuthorName>
            <Gender>男</Gender>
        </Author>
        <Publisher>
            <PublisherName>西安电子科技大学出版社</PublisherName>
            <PublisherAddress>
                <Province>陕西省</Province>
                <City>西安市</City>
                <AddressDetail>科技路41号西安电子科技大学出版社 (710071)</AddressDetail>
            </PublisherAddress>
        </Publisher>
        <Price>26.00</Price>
        <BookNumber>30</BookNumber>
        <PublishDate>2008-10-01</PublishDate>
        <CatalogDateTime>2010-03-01T14:30:00</CatalogDateTime>
        <InStoreDateTime>2010-04-01T14:00:00</InStoreDateTime>
    </Book>
</Library>

=== LviatYi/KnownBase/XML/instance/e-library-instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="e-library.css" type="text/css"?>
<Library xmlns="http://lviat.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://lviat.com e-library.xsd">
    <Book ISBN="978-7-0403-7256-4">
        <BookName>软件开发与项目管理</BookName>
        <Author>
            <AuthorName>朱利华</AuthorName>
            <Gender>女</Gender>
        </Author>
        <Author>
            <AuthorName>郭永洪</AuthorName>
            <Gender>男</Gender>
        </Author>
        <Publisher>
            <PublisherName>高等教育出版社</PublisherName>
            <PublisherAddress>
                <Province>北京市</Province>
                <City>西城区</City>
                <AddressDetail>北京市西城区德外大街4号 (100120)</AddressDetail>
            </PublisherAddress>
        </Publisher>
        <Price>33.80</Price>
        <BookNumber>20</BookNumber>
        <PublishDate>2013-04-01</PublishDate>
        <CatalogDateTime>2014-02-10T14:30:00</CatalogDateTime>
        <InStoreDateTime>2014-03-10T12:00:00</InStoreDateTime>
    </Book>
</Library>
